---

- name: Install linters (pip)
  pip:
    name: "{{ item }}"
    state: latest
  with_items:
    - ansible-lint
    - catkin-lint
    - cmakelint
    - flake8
    - yamllint

- name: Install linters (npm)
  npm:
    name: "{{ item }}"
    state: latest
    global: yes
  with_items:
    - dockerlint

- name: Install linters (Homebrew)
  homebrew:
    name: "{{ item }}"
    state: latest
  with_items:
    - clang-format
    - shellcheck
