---

- name: Homebrew update and upgrade
  homebrew:
    update_homebrew: yes
    upgrade_all: yes

- name: Install iTerm2
  homebrew_cask:
    cask: iterm2
    state: present

- name: Install the basics
  homebrew:
    formula: "{{ item }}"
    state: present
  with_items:
    - git
    - python

- name: Install XQuartz
  homebrew_cask:
    cask: xquartz
    state: present

- name: Editors
  include_tasks: editors.yml

- name: Linters
  include_tasks: linters.yml

- name: VMs and Containers
  include_tasks: virtualization.yml
