---

- name: Install editors (Homebrew)
  homebrew:
    name: "{{ item }}"
    state: latest
  with_items:
    - vim

- name: Install editors (Homebrew cask)
  homebrew_cask:
    name: "{{ item }}"
    state: present
  with_items:
    - atom
